// data 
const quotes = [
  "The only way to do great work is to love what you do.",
  "In the middle of every difficulty lies opportunity.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Be yourself; everyone else is already taken.",
  "Do what you can, with what you have, where you are.",
  "Happiness depends upon ourselves.",
  "It does not matter how slowly you go as long as you do not stop.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Don't cry because it's over, smile because it happened.",
  "Life is what happens when you're making other plans.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Act as if what you do makes a difference. It does.",
  "The best way to predict your future is to create it.",
  "Believe you can and you're halfway there.",
  "You miss 100% of the shots you don’t take.",
  "Strive not to be a success, but rather to be of value.",
  "Dream big and dare to fail.",
  "What we think, we become.",
  "Action is the foundational key to all success.",
  "The secret of getting ahead is getting started.",
  "It always seems impossible until it’s done.",
  "Your time is limited, so don't waste it living someone else's life.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "The power of imagination makes us infinite.",
  "Don't let yesterday take up too much of today.",
  "If you are going through hell, keep going.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "Everything has beauty, but not everyone sees it.",
  "Change your thoughts and you change your world.",
  "Simplicity is the ultimate sophistication.",
  "Life is either a daring adventure or nothing at all.",
  "The mind is everything. What you think you become.",
  "An unexamined life is not worth living.",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
  "Innovation distinguishes between a leader and a follower.",
  "If you want to lift yourself up, lift up someone else.",
  "Limit your 'always' and your 'nevers.'",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "Knowledge speaks, but wisdom listens.",
  "It is never too late to be what you might have been.",
  "Either you run the day, or the day runs you.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t watch the clock; do what it does. Keep going.",
  "You must be the change you wish to see in the world.",
  "The purpose of our lives is to be happy.",
  "Go confidently in the direction of your dreams.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "The way to get started is to quit talking and begin doing.",
  "Life is short, and it is up to you to make it sweet.",
  "The best revenge is massive success.",
  "The only person you are destined to become is the person you decide to be.",
  "A year from now you may wish you had started today.",
  "I find that the harder I work, the more luck I seem to have.",
  "Great things never come from comfort zones.",
  "Don’t be afraid to give up the good to go for the great.",
  "Small steps in the right direction can turn out to be the biggest steps of your life.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Opportunities don't happen. You create them.",
  "If you tell the truth, you don't have to remember anything.",
  "Be so good they can’t ignore you.",
  "The only true wisdom is in knowing you know nothing.",
  "Persistence guarantees that results are inevitable.",
  "Integrity is doing the right thing, even when no one is watching.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "Make each day your masterpiece.",
  "The journey of a thousand miles begins with one step.",
  "Keep calm and carry on.",
  "Quality is not an act, it is a habit.",
  "Everything you can imagine is real.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "A person who never made a mistake never tried anything new.",
  "Creativity is intelligence having fun.",
  "Courage is grace under pressure.",
  "The road to success and the road to failure are almost exactly the same.",
  "Don't let the noise of others' opinions drown out your own inner voice.",
  "The starting point of all achievement is desire.",
  "Doubt kills more dreams than failure ever will.",
  "If you can dream it, you can do it.",
  "Turn your wounds into wisdom.",
  "Focus on being productive instead of busy.",
  "Dreaming, after all, is a form of planning.",
  "Work hard in silence, let your success be your noise.",
  "Every moment is a fresh beginning.",
  "He who has a why to live can bear almost any how.",
  "Silence is a source of great strength.",
  "A goal is a dream with a deadline.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Be the reason someone smiles today.",
  "The scariest moment is always just before you start.",
  "You do not find the happy life. You make it.",
  "The sun himself is weak when he first rises, and gathers strength as the day gets on.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Whatever you are, be a good one.",
  "Don't stay in bed unless you can make money in bed.",
  "A smooth sea never made a skilled sailor.",
  "Try to be a rainbow in someone else's cloud.",
  "The best way out is always through.",
  "Your passion is waiting for your courage to catch up."
];

let box = document.getElementById('quote-box');

let ele = document.getElementById('quote-text');

function handleClick(){
    ele.textContent = quotes[Math.floor(Math.random()*100)];
    box.append(ele);
}